package com.aethercore.core.m1e3;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.junit.jupiter.api.Assertions.*;

/**
 * M1-E3 Test Suite 2:
 * Laboratory experiments on Java Records:
 * Compact constructors, auto-generated accessors/equals/hashCode,
 * wither pattern, and shallow immutability protection with defensive copies.
 */
public class RecordExperimentsTest {

    private static final UUID PLAYER_ID = UUID.fromString("00000000-0000-0000-0000-000000000001");

    @Nested
    @DisplayName("Thí nghiệm B5: CharacterStats Record baseline")
    class CharacterStatsTests {

        @Test
        @DisplayName("Record auto-generates component accessors, equals(), hashCode(), and toString()")
        void recordAutoGeneratedMethods() {
            CharacterStats stats1 = new CharacterStats(18, 14, 12);
            CharacterStats stats2 = new CharacterStats(18, 14, 12);
            CharacterStats stats3 = new CharacterStats(10, 14, 12);

            // Accessors
            assertEquals(18, stats1.strength());
            assertEquals(14, stats1.intelligence());
            assertEquals(12, stats1.agility());

            // Equals & HashCode
            assertEquals(stats1, stats2);
            assertEquals(stats1.hashCode(), stats2.hashCode());
            assertNotEquals(stats1, stats3);

            // ToString
            assertTrue(stats1.toString().contains("strength=18"));
        }

        @Test
        @DisplayName("Compact constructor validates invariants and throws on invalid inputs")
        void compactConstructorValidation() {
            assertThatThrownBy(() -> new CharacterStats(-1, 10, 10))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("Stats components must be non-negative");
        }

        @Test
        @DisplayName("Record immutability requires creating new instance for modifications (Wither pattern)")
        void witherPatternCreatesNewInstance() {
            CharacterStats initial = new CharacterStats(10, 12, 14);
            CharacterStats buffed = initial.withStrength(15);

            assertEquals(10, initial.strength(), "Initial record must remain unmodified");
            assertEquals(15, buffed.strength(), "New record reflects updated component");
            assertNotSame(initial, buffed);
        }
    }

    @Nested
    @DisplayName("Thí nghiệm B6: Shallow Immutability & Defensive Copying")
    class ShallowImmutabilityTests {

        @Test
        @DisplayName("Unsafe Record without defensive copy allows external mutation of internal list state")
        void unsafeRecordAllowsMutation() {
            List<String> mutableList = new ArrayList<>();
            mutableList.add("Wooden Sword");
            mutableList.add("Health Potion");

            UnsafeInventoryBag unsafeBag = new UnsafeInventoryBag(PLAYER_ID, mutableList);
            assertEquals(2, unsafeBag.items().size());

            // Mutate external list after record construction
            mutableList.add("Stolen Gold");

            // The record state has been mutated from the outside!
            assertEquals(3, unsafeBag.items().size(), "Unsafe record state leaked and changed when external list was modified");
            assertTrue(unsafeBag.items().contains("Stolen Gold"));
        }

        @Test
        @DisplayName("Safe Record with defensive copy protects internal list state from external mutation")
        void safeRecordProtectsState() {
            List<String> mutableList = new ArrayList<>();
            mutableList.add("Wooden Sword");
            mutableList.add("Health Potion");

            InventoryBag safeBag = new InventoryBag(PLAYER_ID, mutableList);
            assertEquals(2, safeBag.items().size());

            // Attempt 1: Mutate original source list
            mutableList.add("Stolen Gold");
            assertEquals(2, safeBag.items().size(), "Safe record must not be affected by mutations on original list");
            assertFalse(safeBag.items().contains("Stolen Gold"));

            // Attempt 2: Mutate via accessor
            assertThrows(UnsupportedOperationException.class, () -> {
                safeBag.items().add("Cheat Item");
            }, "List returned by accessor must be unmodifiable");
        }
    }
}
